services:
  db_mariadb:
    container_name: nightforge_db_mariadb
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nightforge
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - '3311:3306'
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    container_name: nightforge_phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db_mariadb
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - '7501:80'
    networks:
      - app-network

networks:
  app-network:

volumes:
  database_data:
